# Generated by Django 3.1.7 on 2021-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopifyUserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "myshopify_domain",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "token",
                    models.CharField(
                        default="00000000000000000000000000000000",
                        editable=False,
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
